"""add camera fields to project

Revision ID: 897dbfa81f80
Revises: 
Create Date: 2026-06-01 11:39:53.842640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '897dbfa81f80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotation_projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camera_url', sa.String(length=500), nullable=True, comment='摄像头ISAPI地址，如 http://192.168.1.64'))
        batch_op.add_column(sa.Column('camera_username', sa.String(length=100), nullable=True, comment='摄像头用户名'))
        batch_op.add_column(sa.Column('camera_password', sa.String(length=500), nullable=True, comment='摄像头密码(加密存储)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotation_projects', schema=None) as batch_op:
        batch_op.drop_column('camera_password')
        batch_op.drop_column('camera_username')
        batch_op.drop_column('camera_url')

    # ### end Alembic commands ###
